### ISSUE TITLE
I cannot setup lindraw...

### ISSUE THREAD

**Issue by ghost** [mtoshi/linkdraw#3]
Hi,

 I excute " bash utils/setup.sh /path/to/linkdraw", then below error messages show.

[root@hoge ~/linkdraw]# bash utils/setup.sh /var/www/html/
cp: target `/var/www/html//configs/' is not a directory
chmod: cannot access`/var/www/html//configs/*.json': No such file or directory

Does "/path/to/linkdraw" mean "web server's contents directory" ??

Other comment
 : I cannot know file version, tell me how to cofirm file version.

Thanx

**Comment by mtoshi** [comment]
I added "configs/" to repo.

regards.
